2020-05-08 22:46:54,696 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-08 22:49:30,063 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:23:35,557 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:24:22,635 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:24:39,466 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:24:39] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:24:42,903 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:24:42] "[37mGET /register HTTP/1.1[0m" 200 -
2020-05-09 01:25:01,426 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:25:01] "[37mPOST /register HTTP/1.1[0m" 200 -
2020-05-09 01:26:33,116 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:26:49,517 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:26:49] "[32mPOST /register HTTP/1.1[0m" 302 -
2020-05-09 01:26:49,609 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:26:49] "[37mGET /login HTTP/1.1[0m" 200 -
2020-05-09 01:26:55,869 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:26:55] "[32mPOST /login HTTP/1.1[0m" 302 -
2020-05-09 01:26:55,945 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:26:55] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:27:00,162 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:27:00] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 01:27:02,161 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:27:02] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:28:14,147 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:28:18,367 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:28:18] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:28:19,828 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:28:19] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:33:56,371 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:34:00,537 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:34:00] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:34:02,082 ERROR main Exception on /add_cloth [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 381, in add_cloth
    return render_template('add_cloth.html', title='Добавление ткани', form=form)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\add_cloth.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\base.html", line 1, in top-level template code
    {% extends "base_without_auth_block.html" %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\base_without_auth_block.html", line 17, in top-level template code
    {% block main %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\add_cloth.html", line 75, in block "main"
    {{ form.usage(class="form-control") }}<br>
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\fields\core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\widgets\core.py", line 323, in __call__
    for val, label, selected in field.iter_choices():
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\fields\core.py", line 454, in iter_choices
    for value, label in self.choices:
ValueError: too many values to unpack (expected 2)
2020-05-09 01:34:02,215 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:34:02] "[35m[1mGET /add_cloth HTTP/1.1[0m" 500 -
2020-05-09 01:35:52,088 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:35:57,844 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:35:57] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:35:59,371 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:35:59] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:36:59,979 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:37:06,986 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:37:06] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:37:08,416 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:37:08] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:37:49,998 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:37:49] "[37mPOST /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:39:30,950 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:39:52,934 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:39:52] "[37mPOST /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:41:47,640 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:42:01,459 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:42:01] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:42:02,702 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:42:02] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:42:42,690 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:42:42] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 01:42:53,427 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:42:53] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:42:53,543 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:42:53] "[37mGET /static/img/cloth/image_30.png HTTP/1.1[0m" 200 -
2020-05-09 01:42:59,186 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:42:59] "[37mGET /view/1 HTTP/1.1[0m" 200 -
2020-05-09 01:49:05,514 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 01:49:14,804 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:49:14] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:49:19,274 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:49:19] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:50:01,546 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:50:01] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 01:50:02,142 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:50:02] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:50:02,285 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:50:02] "[37mGET /static/img/cloth/image_34.png HTTP/1.1[0m" 200 -
2020-05-09 01:50:05,354 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:50:05] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:50:48,068 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:50:48] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 01:50:48,829 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:50:48] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:50:49,022 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:50:49] "[37mGET /static/img/cloth/image_39.png HTTP/1.1[0m" 200 -
2020-05-09 01:51:03,787 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:51:03] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:51:28,797 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:51:28] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:52:04,445 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:52:04] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 01:52:05,317 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:52:05] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:52:05,512 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:52:05] "[37mGET /static/img/cloth/image_44.png HTTP/1.1[0m" 200 -
2020-05-09 01:52:07,628 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:52:07] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:52:47,622 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:52:47] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 01:52:48,777 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:52:48] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:52:48,990 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:52:48] "[37mGET /static/img/cloth/image_48.png HTTP/1.1[0m" 200 -
2020-05-09 01:52:50,707 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:52:50] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 01:53:39,679 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:53:39] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 01:53:41,002 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:53:41] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:53:41,210 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:53:41] "[37mGET /static/img/cloth/image_52.png HTTP/1.1[0m" 200 -
2020-05-09 01:53:45,422 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:53:45] "[37mGET /favourites HTTP/1.1[0m" 200 -
2020-05-09 01:53:48,141 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:53:48] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 01:53:50,787 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:53:50] "[37mGET /view/3 HTTP/1.1[0m" 200 -
2020-05-09 01:53:52,209 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:53:52] "[37mGET /favourites/3 HTTP/1.1[0m" 200 -
2020-05-09 01:53:53,050 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:53:53] "[37mGET /view/3 HTTP/1.1[0m" 200 -
2020-05-09 01:53:56,433 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:53:56] "[37mGET /favourites HTTP/1.1[0m" 200 -
2020-05-09 01:54:00,253 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:54:00] "[37mGET /view/3 HTTP/1.1[0m" 200 -
2020-05-09 01:54:04,574 INFO werkzeug 127.0.0.1 - - [09/May/2020 01:54:04] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 02:06:17,199 INFO werkzeug  * Running on http://0.0.0.0:33507/ (Press CTRL+C to quit)
2020-05-09 02:06:37,123 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:23:45,445 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:23:54,074 ERROR main Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 151, in main_page
    country = get('/api' + f'/countries{cloth.country_id}').json()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/api/countries1': No schema supplied. Perhaps you meant http:///api/countries1?
2020-05-09 02:23:54,227 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:23:54] "[35m[1mGET / HTTP/1.1[0m" 500 -
2020-05-09 02:24:42,733 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:24:47,503 ERROR main Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 151, in main_page
    country = get('/api' + f'/countries/{cloth.country_id}').json()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/api/countries/1': No schema supplied. Perhaps you meant http:///api/countries/1?
2020-05-09 02:24:47,515 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:24:47] "[35m[1mGET / HTTP/1.1[0m" 500 -
2020-05-09 02:25:42,274 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:25:47,554 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:25:47] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:25:49,592 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:25:49] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:25:51,631 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:25:51] "[31m[1mGET /api/countries/2 HTTP/1.1[0m" 400 -
2020-05-09 02:25:53,676 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:25:53] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:25:55,715 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:25:55] "[31m[1mGET /api/countries/3 HTTP/1.1[0m" 400 -
2020-05-09 02:25:57,771 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:25:57] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:25:57,955 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:25:57] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 02:26:36,411 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:27:04,481 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:27:04] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:31:51,425 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:31:56,826 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:31:56] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:31:58,850 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:31:58] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:32:01,077 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:32:01] "[31m[1mGET /api/countries/2 HTTP/1.1[0m" 400 -
2020-05-09 02:32:03,160 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:32:03] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:32:05,206 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:32:05] "[31m[1mGET /api/countries/3 HTTP/1.1[0m" 400 -
2020-05-09 02:32:07,238 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:32:07] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:32:07,322 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:32:07] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 02:32:13,874 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:32:13] "[37mGET /view/2 HTTP/1.1[0m" 200 -
2020-05-09 02:33:10,139 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:33:15,696 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:33:15] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:33:56,406 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:34:01,725 ERROR main Exception on /api/countries/1 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\YandexWebProject\resources\all_resources.py", line 84, in get
    api_key = self.parser.parse_args().get('api_key', default=None)
TypeError: get() takes no keyword arguments
2020-05-09 02:34:01,815 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:34:01] "[35m[1mGET /api/countries/1 HTTP/1.1[0m" 500 -
2020-05-09 02:38:19,947 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:39:11,491 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:39:15,591 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:15] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:39:17,553 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:17] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:39:17,619 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:17] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:39:19,577 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:19] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:39:19,644 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:19] "[31m[1mGET /api/countries/2 HTTP/1.1[0m" 400 -
2020-05-09 02:39:21,601 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:21] "[31m[1mGET /api/countries/2 HTTP/1.1[0m" 400 -
2020-05-09 02:39:21,669 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:21] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:39:23,627 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:23] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:39:23,693 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:23] "[31m[1mGET /api/countries/3 HTTP/1.1[0m" 400 -
2020-05-09 02:39:25,648 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:25] "[31m[1mGET /api/countries/3 HTTP/1.1[0m" 400 -
2020-05-09 02:39:25,718 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:25] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:39:25,787 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:25] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 02:39:27,671 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:27] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:39:27,687 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:39:27] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 02:43:12,443 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:43:17,944 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:43:17] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:43:19,972 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:43:19] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:43:21,998 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:43:21] "[31m[1mGET /api/countries/2 HTTP/1.1[0m" 400 -
2020-05-09 02:43:24,025 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:43:24] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:43:26,049 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:43:26] "[31m[1mGET /api/countries/3 HTTP/1.1[0m" 400 -
2020-05-09 02:43:28,070 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:43:28] "[31m[1mGET /api/countries/1 HTTP/1.1[0m" 400 -
2020-05-09 02:43:28,134 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:43:28] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 02:45:18,201 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:45:35,665 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:45:42,686 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:45:42] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:45:44,722 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:45:44] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:45:46,753 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:45:46] "[37mGET /api/countries/2 HTTP/1.1[0m" 200 -
2020-05-09 02:45:48,789 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:45:48] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:45:50,820 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:45:50] "[37mGET /api/countries/3 HTTP/1.1[0m" 200 -
2020-05-09 02:45:52,863 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:45:52] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:45:52,931 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:45:52] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 02:46:17,131 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:46:22,921 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:46:22] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:51:53,203 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:51:55,583 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:51:55] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:51:57,482 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:51:57] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:51:57,781 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:51:57] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:51:59,512 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:51:59] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:51:59,817 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:51:59] "[37mGET /api/countries/2 HTTP/1.1[0m" 200 -
2020-05-09 02:52:01,544 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:52:01] "[37mGET /api/countries/2 HTTP/1.1[0m" 200 -
2020-05-09 02:52:01,858 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:52:01] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:52:03,576 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:52:03] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:52:03,890 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:52:03] "[37mGET /api/countries/3 HTTP/1.1[0m" 200 -
2020-05-09 02:52:05,605 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:52:05] "[37mGET /api/countries/3 HTTP/1.1[0m" 200 -
2020-05-09 02:52:05,934 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:52:05] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:52:06,002 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:52:06] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 02:52:07,638 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:52:07] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:52:07,653 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:52:07] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 02:52:29,804 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:52:44,930 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:52:44] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:53:30,222 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:53:33,439 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:53:33] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:53:33,452 ERROR main Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 152, in main_page
    cloth.country_id = country.get('title', default='Неизвестно')
TypeError: get() takes no keyword arguments
2020-05-09 02:53:33,479 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:53:33] "[35m[1mGET / HTTP/1.1[0m" 500 -
2020-05-09 02:53:34,381 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:53:34] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:53:34,399 ERROR main Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 152, in main_page
    cloth.country_id = country.get('title', default='Неизвестно')
TypeError: get() takes no keyword arguments
2020-05-09 02:53:34,407 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:53:34] "[35m[1mGET / HTTP/1.1[0m" 500 -
2020-05-09 02:53:39,114 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:53:39] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:53:39,128 ERROR main Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 152, in main_page
    cloth.country_id = country.get('title', default='Неизвестно')
TypeError: get() takes no keyword arguments
2020-05-09 02:53:39,134 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:53:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
2020-05-09 02:53:54,289 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:53:56,598 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:53:56] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:53:56,611 ERROR main Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 152, in main_page
    cloth.country_id = country.get('title', default='Неизвестно')
TypeError: get() takes no keyword arguments
2020-05-09 02:53:56,633 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:53:56] "[35m[1mGET / HTTP/1.1[0m" 500 -
2020-05-09 02:55:14,234 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:55:20,490 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:55:20] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:57:40,509 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 02:57:45,776 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:57:45] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:57:47,809 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:57:47] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:57:49,844 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:57:49] "[37mGET /api/countries/2 HTTP/1.1[0m" 200 -
2020-05-09 02:57:51,880 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:57:51] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:57:53,923 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:57:53] "[37mGET /api/countries/3 HTTP/1.1[0m" 200 -
2020-05-09 02:57:55,956 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:57:55] "[37mGET /api/countries/1 HTTP/1.1[0m" 200 -
2020-05-09 02:57:56,020 INFO werkzeug 127.0.0.1 - - [09/May/2020 02:57:56] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 03:03:30,396 INFO werkzeug  * Running on http://0.0.0.0:33507/ (Press CTRL+C to quit)
2020-05-09 03:03:51,871 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 03:03:56,599 INFO werkzeug 127.0.0.1 - - [09/May/2020 03:03:56] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:11:34,136 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:14:05,216 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:14:05] "[36mGET /static/css/style_v36.css HTTP/1.1[0m" 304 -
2020-05-09 20:14:05,375 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:14:05] "[36mGET /static/img/cloth/image_39.png HTTP/1.1[0m" 304 -
2020-05-09 20:14:05,395 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:14:05] "[36mGET /static/img/cloth/image_52.png HTTP/1.1[0m" 304 -
2020-05-09 20:14:05,405 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:14:05] "[36mGET /static/img/cloth/image_30.png HTTP/1.1[0m" 304 -
2020-05-09 20:14:05,439 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:14:05] "[36mGET /static/img/cloth/image_44.png HTTP/1.1[0m" 304 -
2020-05-09 20:14:05,443 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:14:05] "[36mGET /static/img/cloth/image_48.png HTTP/1.1[0m" 304 -
2020-05-09 20:14:05,463 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:14:05] "[36mGET /static/img/cloth/image_34.png HTTP/1.1[0m" 304 -
2020-05-09 20:14:05,757 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:14:05] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2020-05-09 20:14:18,608 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:14:18] "[37mGET /view/2 HTTP/1.1[0m" 200 -
2020-05-09 20:14:19,885 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:14:19] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:19:59,590 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:20:19,325 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:20:19] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:20:28,181 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:20:28] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 20:20:31,252 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:20:31] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 20:20:36,262 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:20:36] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 20:20:40,219 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:20:40] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 20:36:05,113 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:36:15,996 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:36:15] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 20:36:19,132 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:36:19] "[37mGET /view/1 HTTP/1.1[0m" 200 -
2020-05-09 20:36:24,353 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:36:24] "[37mGET /1 HTTP/1.1[0m" 200 -
2020-05-09 20:38:15,284 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:38:15] "[37mPOST /1 HTTP/1.1[0m" 200 -
2020-05-09 20:38:52,673 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:38:52] "[32mPOST /1 HTTP/1.1[0m" 302 -
2020-05-09 20:38:54,665 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:38:54] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:38:54,787 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:38:54] "[37mGET /static/img/cloth/image_56.png HTTP/1.1[0m" 200 -
2020-05-09 20:44:05,575 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:44:16,263 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:44:16] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:44:20,812 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:44:20] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 20:44:44,395 ERROR main Exception on /1 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 415, in edit_cloth
    form.usage.data = usage['TypesClothsByUsage'].get('title', '')
KeyError: 'TypesClothsByUsage'
2020-05-09 20:44:44,460 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:44:44] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
2020-05-09 20:46:40,992 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:46:49,697 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:46:49] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:46:55,096 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:46:55] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 20:47:50,896 ERROR main Exception on /view/1 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 188, in view_cloth
    cloth.cloth_type_by_usage_id = usage['TypesClothsByUsage'].get('title', 'Неизвестно')
KeyError: 'TypesClothsByUsage'
2020-05-09 20:47:50,906 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:47:50] "[35m[1mGET /view/1 HTTP/1.1[0m" 500 -
2020-05-09 20:48:08,933 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:48:14,386 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:48:14] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:48:15,943 ERROR main Exception on /view/1 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 188, in view_cloth
    cloth.cloth_type_by_usage_id = usage['TypesClothsByUsage'].get('title', 'Неизвестно')
KeyError: 'TypesClothsByUsage'
2020-05-09 20:48:15,949 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:48:15] "[35m[1mGET /view/1 HTTP/1.1[0m" 500 -
2020-05-09 20:49:21,232 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:49:41,637 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:49:41] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:49:45,593 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:49:45] "[37mGET /view/4 HTTP/1.1[0m" 200 -
2020-05-09 20:50:34,846 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:50:35,894 ERROR main Exception on /4 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 454, in edit_cloth
    return render_template('add_cloth.html', title='Редактирование ткани', form=form)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\add_cloth.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\base.html", line 1, in top-level template code
    {% extends "base_without_auth_block.html" %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\base_without_auth_block.html", line 17, in top-level template code
    {% block main %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\add_cloth.html", line 75, in block "main"
    {{ form.usage(class="form-control") }}<br>
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\fields\core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\widgets\core.py", line 323, in __call__
    for val, label, selected in field.iter_choices():
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\fields\core.py", line 488, in iter_choices
    selected = self.data is not None and self.coerce(value) in self.data
TypeError: 'in <string>' requires string as left operand, not int
2020-05-09 20:50:36,033 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:50:36] "[35m[1mGET /4 HTTP/1.1[0m" 500 -
2020-05-09 20:50:40,821 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:50:40] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:50:45,149 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:50:45] "[37mGET /view/4 HTTP/1.1[0m" 200 -
2020-05-09 20:50:50,110 ERROR main Exception on /4 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 454, in edit_cloth
    return render_template('add_cloth.html', title='Редактирование ткани', form=form)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\add_cloth.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\base.html", line 1, in top-level template code
    {% extends "base_without_auth_block.html" %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\base_without_auth_block.html", line 17, in top-level template code
    {% block main %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\add_cloth.html", line 75, in block "main"
    {{ form.usage(class="form-control") }}<br>
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\fields\core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\widgets\core.py", line 323, in __call__
    for val, label, selected in field.iter_choices():
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\fields\core.py", line 488, in iter_choices
    selected = self.data is not None and self.coerce(value) in self.data
TypeError: 'in <string>' requires string as left operand, not int
2020-05-09 20:50:50,120 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:50:50] "[35m[1mGET /4 HTTP/1.1[0m" 500 -
2020-05-09 20:53:55,038 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:54:06,050 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:54:06] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:54:08,689 ERROR main Exception on /4 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 454, in edit_cloth
    return render_template('add_cloth.html', title='Редактирование ткани', form=form)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\add_cloth.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\base.html", line 1, in top-level template code
    {% extends "base_without_auth_block.html" %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\base_without_auth_block.html", line 17, in top-level template code
    {% block main %}
  File "C:\Users\User\PycharmProjects\YandexWebProject\templates\add_cloth.html", line 84, in block "main"
    {{ form.type(class="form-control") }}<br>
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\fields\core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\widgets\core.py", line 323, in __call__
    for val, label, selected in field.iter_choices():
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\wtforms\fields\core.py", line 488, in iter_choices
    selected = self.data is not None and self.coerce(value) in self.data
TypeError: 'in <string>' requires string as left operand, not int
2020-05-09 20:54:08,707 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:54:08] "[35m[1mGET /4 HTTP/1.1[0m" 500 -
2020-05-09 20:54:50,840 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:54:55,614 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:54:55] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:54:58,520 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:54:58] "[37mGET /4 HTTP/1.1[0m" 200 -
2020-05-09 20:55:07,273 ERROR main Exception on /1 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 415, in edit_cloth
    form.usage.data = usage['TypesClothsByUsage'].get('title', '')
KeyError: 'TypesClothsByUsage'
2020-05-09 20:55:07,285 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:55:07] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
2020-05-09 20:55:19,755 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:55:22,897 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:55:22] "[32mGET /delete/1 HTTP/1.1[0m" 302 -
2020-05-09 20:55:24,157 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:55:24] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 20:55:28,197 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:55:28] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 20:56:39,583 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:56:39] "[37mPOST /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 20:57:36,433 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:57:55,590 ERROR main Exception on /add_cloth [POST]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 8 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 393, in add_cloth
    session.commit()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1036, in commit
    self.transaction.commit()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 503, in commit
    self._prepare_impl()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 482, in _prepare_impl
    self.session.flush()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2479, in flush
    self._flush(objects)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2577, in _flush
    flush_context.execute()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    insert,
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1137, in _emit_insert_statements
    statement, params
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 8 - probably unsupported type.
[SQL: INSERT INTO cloths (title, description, images_links, colors, length, price, date, country_id, cloth_type_id, cloth_type_by_usage_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('Штапель', '100% хлопок', '/static/img/cloth/image_60.png;/static/img/cloth/image_61.png;/static/img/cloth/image_62.png;/static/img/cloth/image_63.png', 'Изумрудный', 40.9, 123, '2020-05-09', 4, ['49'], ['1', '23'])]
(Background on this error at: http://sqlalche.me/e/rvf5)
2020-05-09 20:57:55,846 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:57:55] "[35m[1mPOST /add_cloth HTTP/1.1[0m" 500 -
2020-05-09 20:58:26,408 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 20:58:52,694 ERROR main Exception on /add_cloth [POST]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 8 - probably unsupported type.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 393, in add_cloth
    session.commit()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1036, in commit
    self.transaction.commit()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 503, in commit
    self._prepare_impl()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 482, in _prepare_impl
    self.session.flush()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2479, in flush
    self._flush(objects)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2577, in _flush
    flush_context.execute()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    insert,
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1137, in _emit_insert_statements
    statement, params
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 8 - probably unsupported type.
[SQL: INSERT INTO cloths (title, description, images_links, colors, length, price, date, country_id, cloth_type_id, cloth_type_by_usage_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('Штапель', '100% хлопок', '/static/img/cloth/image_64.png;/static/img/cloth/image_65.png;/static/img/cloth/image_66.png;/static/img/cloth/image_67.png', 'Изумрудный', 40.9, 123, '2020-05-09', 4, ['49'], ['1', '23'])]
(Background on this error at: http://sqlalche.me/e/rvf5)
2020-05-09 20:58:52,735 INFO werkzeug 127.0.0.1 - - [09/May/2020 20:58:52] "[35m[1mPOST /add_cloth HTTP/1.1[0m" 500 -
2020-05-09 20:59:33,050 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 21:09:01,856 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 21:09:13,414 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:09:13] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 21:09:16,689 ERROR main Exception on /4 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 407, in edit_cloth
    usages_id = [usage_id for usage_id in cloth.cloth_type_by_usage_id.split(DIVISOR)]
AttributeError: 'int' object has no attribute 'split'
2020-05-09 21:09:16,703 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:09:16] "[35m[1mGET /4 HTTP/1.1[0m" 500 -
2020-05-09 21:14:47,380 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 21:15:42,552 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 21:16:03,332 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:16:03] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 21:16:08,664 ERROR main Exception on /4 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 407, in edit_cloth
    usages_id = [usage_id for usage_id in cloth.cloth_type_by_usage_id.split(DIVISOR)]
AttributeError: 'int' object has no attribute 'split'
2020-05-09 21:16:08,682 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:16:08] "[35m[1mGET /4 HTTP/1.1[0m" 500 -
2020-05-09 21:21:11,855 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 21:21:16,452 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:21:16] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 21:21:19,986 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:21:19] "[37mGET /login HTTP/1.1[0m" 200 -
2020-05-09 21:21:21,853 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:21:21] "[37mGET /register HTTP/1.1[0m" 200 -
2020-05-09 21:21:52,883 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:21:52] "[32mPOST /register HTTP/1.1[0m" 302 -
2020-05-09 21:21:52,922 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:21:52] "[37mGET /login HTTP/1.1[0m" 200 -
2020-05-09 21:21:59,371 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:21:59] "[32mPOST /login HTTP/1.1[0m" 302 -
2020-05-09 21:21:59,424 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:21:59] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 21:22:02,737 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:22:02] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 21:24:36,026 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 21:24:45,953 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:24:45] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 21:24:47,805 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:24:47] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 21:25:44,573 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:25:44] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 21:25:44,963 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:25:44] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 21:25:45,135 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:25:45] "[37mGET /static/img/cloth/image_68.png HTTP/1.1[0m" 200 -
2020-05-09 21:25:50,391 ERROR main Exception on /view/1 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 188, in view_cloth
    cloth.cloth_type_by_usage_id = usage['TypesClothsByUsage'].get('title', 'Неизвестно')
KeyError: 'TypesClothsByUsage'
2020-05-09 21:25:50,400 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:25:50] "[35m[1mGET /view/1 HTTP/1.1[0m" 500 -
2020-05-09 21:38:27,055 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 21:38:32,791 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:38:32] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 21:38:40,234 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:38:40] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 21:38:42,452 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:38:42] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 21:38:45,135 INFO werkzeug 127.0.0.1 - - [09/May/2020 21:38:45] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 22:52:37,471 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 22:52:59,446 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:52:59] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 22:53:08,012 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:53:08] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 22:53:12,455 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:53:12] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 22:54:06,570 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:54:06] "[37mPOST /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 22:54:07,424 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:54:07] "[37mPOST /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 22:54:37,742 ERROR root cannot identify image file './static/img/cloth/image_72.png'
2020-05-09 22:54:37,829 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:54:37] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 22:54:39,486 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:54:39] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 22:54:48,637 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:54:48] "[37mGET /view/2 HTTP/1.1[0m" 200 -
2020-05-09 22:55:02,627 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:55:02] "[37mGET /2 HTTP/1.1[0m" 200 -
2020-05-09 22:55:12,969 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:55:12] "[37mPOST /2 HTTP/1.1[0m" 200 -
2020-05-09 22:55:37,757 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:55:37] "[32mPOST /2 HTTP/1.1[0m" 302 -
2020-05-09 22:55:39,464 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:55:39] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 22:55:39,582 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:55:39] "[37mGET /static/img/cloth/image_72.png HTTP/1.1[0m" 200 -
2020-05-09 22:55:43,935 ERROR main Exception on /view/2 [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask_restful\__init__.py", line 272, in error_router
    return original_handler(e)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\User\PycharmProjects\sql_alchemy\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/User/PycharmProjects/YandexWebProject/main.py", line 200, in view_cloth
    usages_titles.append(usage['TypesClothsByUsage'].get('title', 'Неизвестно'))
KeyError: 'TypesClothsByUsage'
2020-05-09 22:55:44,032 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:55:44] "[35m[1mGET /view/2 HTTP/1.1[0m" 500 -
2020-05-09 22:56:16,454 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 22:56:24,217 INFO werkzeug 127.0.0.1 - - [09/May/2020 22:56:24] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:29:02,329 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-05-09 23:29:13,162 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:29:13] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:29:16,349 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:29:16] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:30:44,397 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:30:44] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:30:44,866 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:30:44] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:30:45,014 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:30:45] "[37mGET /static/img/cloth/image_77.png HTTP/1.1[0m" 200 -
2020-05-09 23:30:50,949 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:30:50] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:32:45,363 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:32:45] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:32:57,331 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:32:57] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:32:57,546 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:32:57] "[37mGET /static/img/cloth/image_82.png HTTP/1.1[0m" 200 -
2020-05-09 23:33:07,431 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:33:07] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:36:56,422 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:36:56] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:36:57,356 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:36:57] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:36:57,534 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:36:57] "[37mGET /static/img/cloth/image_86.png HTTP/1.1[0m" 200 -
2020-05-09 23:37:01,113 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:37:01] "[37mGET /view/4 HTTP/1.1[0m" 200 -
2020-05-09 23:37:15,727 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:37:15] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:39:07,073 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:39:07] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:39:08,292 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:39:08] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:39:08,788 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:39:08] "[37mGET /static/img/cloth/image_90.png HTTP/1.1[0m" 200 -
2020-05-09 23:39:11,636 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:39:11] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:40:47,013 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:40:47] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:40:48,398 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:40:48] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:40:48,624 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:40:48] "[37mGET /static/img/cloth/image_95.png HTTP/1.1[0m" 200 -
2020-05-09 23:40:51,552 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:40:51] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:42:51,493 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:42:51] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:42:53,081 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:42:53] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:42:53,298 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:42:53] "[37mGET /static/img/cloth/image_99.png HTTP/1.1[0m" 200 -
2020-05-09 23:42:54,852 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:42:54] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:44:36,713 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:44:36] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:44:38,625 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:44:38] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:44:38,842 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:44:38] "[37mGET /static/img/cloth/image_103.png HTTP/1.1[0m" 200 -
2020-05-09 23:44:40,453 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:44:40] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:46:44,823 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:46:44] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:46:46,840 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:46:46] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:46:47,076 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:46:47] "[37mGET /static/img/cloth/image_107.png HTTP/1.1[0m" 200 -
2020-05-09 23:46:51,156 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:46:51] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:48:58,257 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:48:58] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:49:00,496 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:49:00] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:49:00,723 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:49:00] "[37mGET /static/img/cloth/image_111.png HTTP/1.1[0m" 200 -
2020-05-09 23:49:03,812 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:49:03] "[37mGET /10 HTTP/1.1[0m" 200 -
2020-05-09 23:49:13,597 ERROR root cannot identify image file './static/img/cloth/image_115.png'
2020-05-09 23:49:13,676 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:49:13] "[32mPOST /10 HTTP/1.1[0m" 302 -
2020-05-09 23:49:16,067 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:49:16] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:49:21,528 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:49:21] "[37mGET /10 HTTP/1.1[0m" 200 -
2020-05-09 23:49:40,485 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:49:40] "[32mPOST /10 HTTP/1.1[0m" 302 -
2020-05-09 23:49:42,800 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:49:42] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:49:43,052 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:49:43] "[37mGET /static/img/cloth/image_115.png HTTP/1.1[0m" 200 -
2020-05-09 23:49:59,093 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:49:59] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:51:18,363 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:51:18] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:51:20,893 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:51:20] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:51:21,119 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:51:21] "[37mGET /static/img/cloth/image_119.png HTTP/1.1[0m" 200 -
2020-05-09 23:51:36,722 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:51:36] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 23:51:43,364 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:51:43] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 23:51:49,779 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:51:49] "[37mPOST / HTTP/1.1[0m" 200 -
2020-05-09 23:52:16,267 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:52:16] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:53:16,827 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:53:16] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:53:19,617 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:53:19] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:53:19,820 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:53:19] "[37mGET /static/img/cloth/image_123.png HTTP/1.1[0m" 200 -
2020-05-09 23:53:33,805 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:53:33] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:55:41,819 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:55:41] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:55:44,777 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:55:44] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:55:45,008 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:55:45] "[37mGET /static/img/cloth/image_127.png HTTP/1.1[0m" 200 -
2020-05-09 23:55:46,702 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:55:46] "[37mGET /add_cloth HTTP/1.1[0m" 200 -
2020-05-09 23:57:20,988 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:57:20] "[32mPOST /add_cloth HTTP/1.1[0m" 302 -
2020-05-09 23:57:24,150 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:57:24] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:57:24,414 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:57:24] "[37mGET /static/img/cloth/image_131.png HTTP/1.1[0m" 200 -
2020-05-09 23:57:32,424 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:57:32] "[37mGET /13 HTTP/1.1[0m" 200 -
2020-05-09 23:58:03,759 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:58:03] "[32mPOST /13 HTTP/1.1[0m" 302 -
2020-05-09 23:58:09,301 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:58:09] "[37mGET / HTTP/1.1[0m" 200 -
2020-05-09 23:58:09,527 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:58:09] "[37mGET /static/img/cloth/image_134.png HTTP/1.1[0m" 200 -
2020-05-09 23:58:22,684 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:58:22] "[37mGET /view/3 HTTP/1.1[0m" 200 -
2020-05-09 23:58:26,093 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:58:26] "[37mGET /view/image?img=/static/img/cloth/image_84.png HTTP/1.1[0m" 200 -
2020-05-09 23:58:26,187 INFO werkzeug 127.0.0.1 - - [09/May/2020 23:58:26] "[37mGET /static/img/cloth/image_84.png HTTP/1.1[0m" 200 -
